services:
  servercore-billing-exporter:
    container_name: servercore-billing-exporter
    build: .
    ports:
      - "9876:9876"
    restart: unless-stopped
    environment:
      TOKEN: ${TOKEN}
